version: '2.1'

services:
  zoo2:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"

  kafka2:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo2:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost


# 启动命令  docker-compose -f .\zk_kafka_single.yml up
# 关闭命令 docker-compose -f .\zk_kafka_single.yml  down